# Generated by Django 6.1.2 on 2026-10-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mensaje',
            new_name='Asistencia',
        ),
    ]
