# Generated by Django 6.1.2 on 2026-10-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_rename_mensaje_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='numero_documento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='whatsapp',
            field=models.IntegerField(),
        ),
    ]
