# Generated by Django 6.1.2 on 2026-10-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_alter_asistencia_numero_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.CharField(),
        ),
    ]
