# Generated by Django 6.1.2 on 2026-10-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0006_alter_asistencia_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='numero_documento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='whatsapp',
            field=models.CharField(max_length=20),
        ),
    ]
